version: "3.7"

services:  
  elasticsearch:
    container_name: "elastic_search"
    build:
        context: .
        dockerfile: ElasticSearch.Dockerfile
    ports:
        - "9200:9200"
        - "9300:9300"
    environment:
        discovery.seed_hosts: "elastic_search"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://elastic_search:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - samrullo_elasticsearch-networks
networks:
  samrullo_elasticsearch-networks:
    driver: bridge
